name: TimingSystemNoBoatCollisions
version: 1.1-RC1
main: com.frosthex.timingsystem.noboatcollisions.TimingSystemNoBoatCollisionsPlugin
api-version: 1.19
authors: [JustBru00]
softdepend: [TimingSystem]

commands:
  noboatcollisions:
    description: 'A command that shows details about the TimingSystemNoBoatCollisions add-on plugin.'
    aliases: ['nbc']