name: TimingSystemNoBoatCollisions
version: 1.0
main: com.frosthex.timingsystem.noboatcollisions.TimingSystemNoBoatCollisionsPlugin
api-version: 1.20
authors: [JustBru00]
softdepend: [TimingSystem]

commands:
  noboatcollisions:
    description: 'A command that shows details about the TimingSystemNoBoatCollisions add-on plugin.'
    aliases: ['nbc']